# Generated by Django 5.0.2 on 2024-06-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='pdf',
            new_name='file',
        ),
    ]
